// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzp-3g8I6p085A6x5znG9qGKDIlqOuIxc',
    appId: '1:521582329269:web:937f384839a50ef0a26dfc',
    messagingSenderId: '521582329269',
    projectId: 'cleancity-ai-9619e',
    authDomain: 'cleancity-ai-9619e.firebaseapp.com',
    storageBucket: 'cleancity-ai-9619e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcvAv2dtI7irqQhV6FoBzaNoXnGjd0FMo',
    appId: '1:521582329269:android:37241d9b2fd451b5a26dfc',
    messagingSenderId: '521582329269',
    projectId: 'cleancity-ai-9619e',
    storageBucket: 'cleancity-ai-9619e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA81Mq5qdB1JCsV1WdvHnnl5-qsHIS7jV0',
    appId: '1:521582329269:ios:c1f2fa88761820faa26dfc',
    messagingSenderId: '521582329269',
    projectId: 'cleancity-ai-9619e',
    storageBucket: 'cleancity-ai-9619e.firebasestorage.app',
    iosBundleId: 'com.example.cleancityAiPixelin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA81Mq5qdB1JCsV1WdvHnnl5-qsHIS7jV0',
    appId: '1:521582329269:ios:c1f2fa88761820faa26dfc',
    messagingSenderId: '521582329269',
    projectId: 'cleancity-ai-9619e',
    storageBucket: 'cleancity-ai-9619e.firebasestorage.app',
    iosBundleId: 'com.example.cleancityAiPixelin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzp-3g8I6p085A6x5znG9qGKDIlqOuIxc',
    appId: '1:521582329269:web:6c96f6153129e524a26dfc',
    messagingSenderId: '521582329269',
    projectId: 'cleancity-ai-9619e',
    authDomain: 'cleancity-ai-9619e.firebaseapp.com',
    storageBucket: 'cleancity-ai-9619e.firebasestorage.app',
  );
}
