// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkhyzbRQ10o5cpl5kpx0sPmzeygyVbDwo',
    appId: '1:533179558094:web:88b4fce74b7b34b8f2c89f',
    messagingSenderId: '533179558094',
    projectId: 'cleancityai',
    authDomain: 'cleancityai.firebaseapp.com',
    storageBucket: 'cleancityai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4JGXiqsO_SXy4leH5qdG5d80QQwwrvcI',
    appId: '1:533179558094:android:571c88178f3ddb7ff2c89f',
    messagingSenderId: '533179558094',
    projectId: 'cleancityai',
    storageBucket: 'cleancityai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgpgAj2I1nmC5SdPm9aYmtN_kj-eqAqcg',
    appId: '1:533179558094:ios:a666a555ec6ca518f2c89f',
    messagingSenderId: '533179558094',
    projectId: 'cleancityai',
    storageBucket: 'cleancityai.firebasestorage.app',
    iosBundleId: 'com.example.cleancityai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgpgAj2I1nmC5SdPm9aYmtN_kj-eqAqcg',
    appId: '1:533179558094:ios:a666a555ec6ca518f2c89f',
    messagingSenderId: '533179558094',
    projectId: 'cleancityai',
    storageBucket: 'cleancityai.firebasestorage.app',
    iosBundleId: 'com.example.cleancityai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkhyzbRQ10o5cpl5kpx0sPmzeygyVbDwo',
    appId: '1:533179558094:web:73db1156e01459a7f2c89f',
    messagingSenderId: '533179558094',
    projectId: 'cleancityai',
    authDomain: 'cleancityai.firebaseapp.com',
    storageBucket: 'cleancityai.firebasestorage.app',
  );
}
